### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by feiyangdezhu** [1991viet/Hierarchical-attention-networks-pytorch#5]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train(opt)
  File "train.py", line 83, in train
    label = label.cuda()
AttributeError: 'tuple' object has no attribute 'cuda'

**Comment by 1991viet** [comment]
Hi,
Did you change anything from the source code, since I could still run normally ?
